### ISSUE TITLE
More projects with OpenVINO

### ISSUE THREAD

**Issue by vurusovs** [openvinotoolkit/awesome-openvino#2]
Please, add next projects to the list:
1. https://github.com/sdcb/OpenVINO.NET
2. https://github.com/intel/openvino-rs
3. https://github.com/RapidAI/RapidOCR

**Comment by p-wysocki** [comment]
Added in https://github.com/openvinotoolkit/awesome-openvino/pull/1

**Comment by Pooja-B** [comment]
This PR is merged. Thanks!
