### ISSUE TITLE
Add some projects from Intel Software Innovators for Edge

### ISSUE THREAD

**Issue by DimaPastushenkov** [openvinotoolkit/awesome-openvino#3]
Add the following projects:
https://github.com/AbhiLegend/DrugDisOpenVINO
https://github.com/guojin-yan/OpenVINO-CSharp-API/tree/csharp3.0/tutorial_examples/PP-Human_Fall_Detection
https://github.com/salvino72/openvino-Tennis-Posture/
https://github.com/AbhiLegend/OpenVinoQuantization

**Comment by Pooja-B** [comment]
Thanks for adding these.
